version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
